# Generated by Django 5.1 on 2024-09-18 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0011_alter_rating_atmosphere_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='venues.venue'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='venues.menu'),
        ),
    ]
