# Generated by Django 5.1 on 2024-10-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0012_alter_menu_venue_alter_menuitems_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='primary_image',
            field=models.FileField(default='/staticfiles/default_photo.webp', upload_to='uploads/'),
        ),
    ]
