# Generated by Django 5.1 on 2024-10-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0013_venue_primary_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='primary_image',
            field=models.FileField(default='/default_photo.webp', upload_to='uploads/'),
        ),
    ]
